In [41]:
import numpy as np
import matplotlib.pyplot as plt
import math
import pandas as pd

In [42]:

def finiteDifference(psi,v,t,x):
    x

In [43]:
def matrixCreator(dX,dT,i,V,N):
    A=np.zeros((N,N))
    for x in range(1,N-1):
        A[x][x-1:x+2]=Insertion(dX,dT,i,V[x])
    A[0][0:2]=Insertion(dX,dT,i,V[0])[1:3]
    A[N-1][N-2:N]=Insertion(dX,dT,i,V[N-1])[0:1]
    print(A)

    
def Insertion(dX,dT,i,V):
    insertArr= np.array([1,dX**2/(i*dT)-2+V,1])
    return insertArr

V=np.linspace(1,5,5)
matrixCreator(1,1,1,V,5)

[[0. 1. 0. 0. 0.]
 [1. 1. 1. 0. 0.]
 [0. 1. 2. 1. 0.]
 [0. 0. 1. 3. 1.]
 [0. 0. 0. 1. 1.]]
